### ISSUE TITLE
关于FLops和参数量

### ISSUE THREAD

**Issue by tangshunpu** [Kylin9511/BCsiNet#1]
请问Encoder和Decoder加起来总共的flops和参数量分别是多少

**Comment by Kylin9511** [comment]
你好，BCsiNet的轻量化对象是encoder，因此文章中也只对encoder的计算量和参数量进行分析对比。这是因为encoder需要部署在用户端，通常种类繁多，资源受限严重，而基站端相对对能耗和算力的要求不那么苛刻。所以在轻量级网络的设计中，encoder的小型化比decoder的小型化更加实用。

关于你提到的decoder的flops和参数量，BCsiNet-A2和原始的CsiNet持平； BCsiNet-B3的decoder相比于BCsiNet-A2大概增加了1.6M的计算量（参数量增加可以忽略不计）。Anyway，decoder的复杂度只要在合理的范围内即可，不是问题的关键。
